# -*- coding: utf-8 -*-
"""ตัวอย่างการส่งงานSec1_Week1_123456789-0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Fvajd6iF0GGB-9lreZsRwhZ0H_UMTA95

Week 1 Sce2 663380347-5 นายธนภัทร สมบูรณ์

Lab 1.1: Environment Setup & First Script
"""

print("Hello, Python Course!")

"""Lab 1.2: Working with Variables and Basic Data Types
- Objective: Students will define variables of different data types, perform simple operations, and display results.

2. Declare and print variables:
"""

Age = 22
GPA = 2.25
Favorite_Color = "Blue"
Student = True

print("Age = ",Age ,type(Age))
print("GPA = ",GPA,type(GPA))
print("Favorite_Color = ",Favorite_Color,type(Favorite_Color))
print("Student = ",Student,type(Student))

"""3. Perform simple arithmetic:

"""

num1 = 7
num2 = 6
sum = num1 + num2
print("Sum = ",sum)

"""4. String concatenation and f-strings:

"""

First_name = "Thanapat"
Last_name = "Somboon"
Full_name = First_name + " " + Last_name
print(f"Hello,{Full_name}")

"""5. User input and type conversion:

"""

num = input("What your favorite number : ")
print("type of A is : ", type(num))
num = int(num)
result = num + 5
print(num," + 5 = ", result)

"""Activity 1.1: Class Discussion - Uses of Scripting
Format: Open discussion, possibly in small groups first, then full class.
Prompt: "Based on the introduction, where do you think scripting with Python could be applied in real-world scenarios? Think about tasks you do daily or things you've seen in other courses."
Expected outcomes: Students will brainstorm and share ideas like automating file operations, simple data analysis, web development, game scripting, scientific computing, etc. Instructor will guide the discussion to highlight Python's versatility.

คำตอบ:ในชีวิตประจำวัน เราสามารถนำทักษะและแนวคิดจากการเขียนโปรแกรมไปประยุกต์ใช้ได้ 2 รูปแบบหลักๆ ดังนี้ครับ

1. การประยุกต์ใช้ในเชิง "กระบวนการคิด" (Computational Thinking)
ทักษะที่ได้จากการเขียนโปรแกรมสามารถนำมาปรับใช้กับการแก้ปัญหาทั่วไปในชีวิตได้ดีมาก:

การย่อยปัญหาใหญ่ (Decomposition): เหมือนการแบ่งโปรเจกต์เขียนโค้ดชิ้นใหญ่ออกเป็นฟังก์ชันย่อยๆ เช่น หากต้องการ "ลดน้ำหนัก" เราจะย่อยออกมาเป็น เรื่องอาหาร การออกกำลังกาย และการนอนหลับ เพื่อให้จัดการง่ายขึ้น

การมองหาแพทเทิร์น (Pattern Recognition): การสังเกตสิ่งที่เป็นไปซ้ำๆ ในชีวิต เช่น ถ้ารถติดทุกวันจันทร์ตอน 8 โมง เราก็ปรับตารางเวลาเพื่อหลีกเลี่ยง เหมือนการเขียนโค้ดดักเงื่อนไข

คิดเป็นขั้นตอน (Algorithm): การจัดลำดับความสำคัญก่อน-หลังอย่างเป็นระบบ เช่น การจัดตารางเวลาทำงาน (To-Do List) เพื่อให้งานเสร็จอย่างมีประสิทธิภาพที่สุด

2. การประยุกต์ใช้ในเชิง "การทำงานจริง" (Practical Automation)
เราสามารถเขียนโปรแกรมง่ายๆ (เช่น ใช้ภาษา Python) เพื่อช่วยลดเวลาการทำงานซ้ำซากในชีวิตประจำวันได้:

การจัดการไฟล์และเอกสาร (Automation): เขียนโค้ดให้เปลี่ยนชื่อไฟล์รูปภาพ 500 รูปในโฟลเดอร์พร้อมกันภายใน 3 วินาที หรือสั่งให้รวมไฟล์ Excel หลายๆ ไฟล์เข้าด้วยกันอัตโนมัติ

การคัดกรองข้อมูล (Data Scraping): เขียนสคริปต์ให้ดึงราคาสินค้าที่เล็งไว้จากเว็บช้อปปิ้งออนไลน์ และส่งแจ้งเตือนเข้า LINE หรือ LINE Notify ทันทีเมื่อราคานั้นลดลงตามที่ตั้งไว้

การบริหารจัดการชีวิต (Personal Tools): สร้างแอปพลิเคชันหรือสเปรดชีตอัจฉริยะส่วนตัวเพื่อคำนวณรายรับ-รายจ่าย หรือคำนวณแคลอรีอาหารที่กินในแต่ละวัน

Activity 1.2: "Python Puzzlers" - Identifying Data Types & Output
Format: Individual or pair work, followed by a class review.
Instructions: Provide a set of small Python code snippets (on a handout or projected). For each snippet, students must:
Predict the output.
Identify the data type of specific variables after certain operations.
Explain why they chose that output/data type.
"""

# Puzzler 1
x = 10
y = 3.5
z = x + y
print(z)
print(type(z))

"""ได้ผลลัพธ์:

เมื่อนำ int มาบวกกับ float ภาษา Python จะแปลงให้เป็น float โดยอัตโนมัติ เพื่อป้องกันไม่ให้ค่าทศนิยมสูญหายในระหว่างการคำนวณ

"""

# Puzzler 2
name = "Alice"
age = "30" # Note: This is a string
message = name + " is " + age + " years old."
print(message)
print(type(age))

"""ได้ผลลัพธ์:

เพราะตัวแปร age ถูกกำหนดค่าให้อยู่ภายในเครื่องหมายคำพูด ("30") จึงมีสถานะเป็นข้อความ (string) และเมื่อนำข้อความทั้งหมดมาใช้เครื่องหมายบวก (+) ภาษา Python จะเป็นการนำข้อความมาต่อกัน (String Concatenation) จนกลายเป็นประโยคยาวที่มีประเภทข้อมูลเป็น str
"""

# Puzzler 3
is_sunny = True
is_raining = False
print(is_sunny and is_raining)
print(type(is_sunny))

"""ได้ผลลัพธ์:

เพราะตัวแปร is_sunny เก็บค่า True ซึ่งเป็นข้อมูลประเภทบูลีน (bool) ส่วนการใช้ตัวดำเนินการตรรกศาสตร์ "and" (และ) ผลลัพธ์จะเป็น True ได้เพียงกรณีเดียวคือเงื่อนไขทั้งสองฝั่งต้องเป็น True พร้อมกัน แต่ในโค้ดนี้ True and False จึงได้ผลลัพธ์ออกมาเป็น False
"""

# Puzzler 4
# What happens here?
# num_str = input("Enter a number: ")
# result = num_str + 5
# print(result)

"""ได้ผลลัพธ์:

เกิดข้อผิดพลาด (TypeError: can only concatenate str (not "int") to str)
ประเภทDataType : ไม่สามารถระบุได้เนื่องจากโปรแกรมหยุดทำงานกลางคัน (Error)
ทำไมถึงเป็นประเภทนี้ : เพราะฟังก์ชัน input() ในภาษา Python จะรับค่าจากผู้ใช้และบันทึกเป็นข้อมูลประเภทข้อความ (str) เสมอ เมื่อโปรแกรมพยายามนำตัวแปร num_str ซึ่งเป็นข้อความ (str) ไปบวกกับตัวเลข 5 ซึ่งเป็นจำนวนเต็ม (int) ภาษา Python จะไม่สามารถรวมข้อมูลต่างประเภทกันในลักษณะนี้ได้ จึงทำให้ระบบแจ้งเตือนข้อผิดพลาดและหยุดทำงานครับ
"""